
export interface Dish {
  name: string;
  ingredients: string[];
  cuisine?: string;
}

export const DISH_DATABASE: Dish[] = [
  // --- 川菜 ---
  { name: "麻婆豆腐", ingredients: ["豆腐", "牛肉", "辣椒", "花椒", "蒜苗"], cuisine: "川菜" },
  { name: "回锅肉", ingredients: ["猪肉", "青椒", "蒜苗", "豆瓣酱"], cuisine: "川菜" },
  { name: "宫保鸡丁", ingredients: ["鸡肉", "花生", "辣椒", "黄瓜"], cuisine: "川菜" },
  { name: "水煮鱼", ingredients: ["草鱼", "豆芽", "辣椒", "花椒"], cuisine: "川菜" },
  { name: "鱼香肉丝", ingredients: ["猪肉", "木耳", "胡萝卜", "笋"], cuisine: "川菜" },
  { name: "夫妻肺片", ingredients: ["牛肉", "牛肚", "牛舌", "花生"], cuisine: "川菜" },
  { name: "辣子鸡", ingredients: ["鸡肉", "辣椒", "花椒", "芝麻"], cuisine: "川菜" },
  { name: "口水鸡", ingredients: ["鸡肉", "花生", "芝麻", "辣椒"], cuisine: "川菜" },
  { name: "毛血旺", ingredients: ["鸭血", "毛肚", "豆芽", "午餐肉"], cuisine: "川菜" },
  { name: "酸菜鱼", ingredients: ["草鱼", "酸菜", "泡椒", "豆芽"], cuisine: "川菜" },
  { name: "担担面", ingredients: ["面条", "猪肉", "花生", "芽菜"], cuisine: "川菜" },
  { name: "灯影牛肉", ingredients: ["牛肉", "芝麻", "辣椒"], cuisine: "川菜" },
  { name: "蚂蚁上树", ingredients: ["粉丝", "猪肉", "豆瓣酱"], cuisine: "川菜" },
  { name: "蒜泥白肉", ingredients: ["猪肉", "大蒜", "黄瓜"], cuisine: "川菜" },
  { name: "干煸肥肠", ingredients: ["猪大肠", "辣椒", "花椒"], cuisine: "川菜" },
  { name: "泡椒牛蛙", ingredients: ["牛蛙", "泡椒", "芹菜"], cuisine: "川菜" },
  { name: "椒麻鸡", ingredients: ["鸡肉", "花椒", "葱"], cuisine: "川菜" },
  { name: "水煮肉片", ingredients: ["猪肉", "豆芽", "青菜"], cuisine: "川菜" },
  { name: "凉拌折耳根", ingredients: ["鱼腥草", "辣椒"], cuisine: "川菜" },
  { name: "怪味鸡丝", ingredients: ["鸡肉", "芝麻酱", "花椒"], cuisine: "川菜" },
  { name: "干烧鲤鱼", ingredients: ["鲤鱼", "猪肉", "芽菜"], cuisine: "川菜" },
  { name: "盐煎肉", ingredients: ["猪肉", "青椒", "豆豉"], cuisine: "川菜" },
  { name: "甜烧白", ingredients: ["猪肉", "糯米", "豆沙"], cuisine: "川菜" },
  { name: "咸烧白", ingredients: ["猪肉", "芽菜", "花椒"], cuisine: "川菜" },
  { name: "火爆腰花", ingredients: ["猪腰", "泡椒", "木耳"], cuisine: "川菜" },
  { name: "肝腰合炒", ingredients: ["猪肝", "猪腰", "蔬菜"], cuisine: "川菜" },
  { name: "冷吃兔", ingredients: ["兔肉", "辣椒", "花椒"], cuisine: "川菜" },
  { name: "泉水鸡", ingredients: ["鸡肉", "泡椒", "香菇"], cuisine: "川菜" },
  { name: "芋儿鸡", ingredients: ["鸡肉", "芋头", "泡椒"], cuisine: "川菜" },
  { name: "豆花牛肉", ingredients: ["牛肉", "豆花", "辣椒"], cuisine: "川菜" },

  // --- 粤菜 ---
  { name: "白切鸡", ingredients: ["鸡肉", "姜", "葱"], cuisine: "粤菜" },
  { name: "烤乳猪", ingredients: ["猪肉", "五香粉", "海鲜酱"], cuisine: "粤菜" },
  { name: "叉烧", ingredients: ["猪肉", "叉烧酱", "蜂蜜"], cuisine: "粤菜" },
  { name: "清蒸鲈鱼", ingredients: ["鲈鱼", "姜", "葱", "豉油"], cuisine: "粤菜" },
  { name: "蚝油牛肉", ingredients: ["牛肉", "蚝油", "青椒"], cuisine: "粤菜" },
  { name: "豉汁蒸排骨", ingredients: ["猪排骨", "豆豉", "蒜"], cuisine: "粤菜" },
  { name: "梅菜扣肉", ingredients: ["猪肉", "梅干菜"], cuisine: "粤菜" },
  { name: "盐焗鸡", ingredients: ["鸡肉", "盐"], cuisine: "粤菜" },
  { name: "煲仔饭", ingredients: ["米饭", "腊肠", "腊肉", "青菜"], cuisine: "粤菜" },
  { name: "老火靓汤", ingredients: ["猪肉", "鸡肉", "药材", "蔬菜"], cuisine: "粤菜" },
  { name: "虾饺", ingredients: ["虾仁", "竹笋", "澄粉"], cuisine: "粤菜" },
  { name: "烧鹅", ingredients: ["鹅肉", "五香粉", "海鲜酱"], cuisine: "粤菜" },
  { name: "肠粉", ingredients: ["米粉", "虾仁", "牛肉", "青菜"], cuisine: "粤菜" },
  { name: "萝卜牛腩", ingredients: ["牛腩", "白萝卜", "柱候酱"], cuisine: "粤菜" },
  { name: "姜葱炒蟹", ingredients: ["螃蟹", "姜", "葱"], cuisine: "粤菜" },
  { name: "清补凉煲鸡", ingredients: ["鸡肉", "药材"], cuisine: "粤菜" },
  { name: "鼓椒炒蛤蜊", ingredients: ["花蛤", "豆豉", "辣椒"], cuisine: "粤菜" },
  { name: "咸鱼鸡粒炒饭", ingredients: ["米饭", "鸡肉", "咸鱼"], cuisine: "粤菜" },
  { name: "冬瓜盅", ingredients: ["冬瓜", "猪肉", "虾仁", "瑶柱"], cuisine: "粤菜" },
  { name: "生炒骨", ingredients: ["猪排骨", "菠萝", "青椒"], cuisine: "粤菜" },
  { name: "西兰花炒带子", ingredients: ["西兰花", "带子", "蒜"], cuisine: "粤菜" },
  { name: "鱼肚羹", ingredients: ["鱼肚", "鸡肉", "香菇"], cuisine: "粤菜" },
  { name: "荷叶饭", ingredients: ["米饭", "鸡肉", "香菇", "荷叶"], cuisine: "粤菜" },
  { name: "姜撞奶", ingredients: ["牛奶", "姜汁"], cuisine: "粤菜" },
  { name: "双皮奶", ingredients: ["牛奶", "鸡蛋"], cuisine: "粤菜" },
  { name: "杨枝甘露", ingredients: ["芒果", "柚子", "西米"], cuisine: "粤菜" },
  { name: "蛋挞", ingredients: ["面粉", "鸡蛋", "牛奶"], cuisine: "粤菜" },
  { name: "老婆饼", ingredients: ["面粉", "冬瓜", "芝麻"], cuisine: "粤菜" },
  { name: "鸡仔饼", ingredients: ["面粉", "猪肉", "花生"], cuisine: "粤菜" },

  // --- 湘菜 ---
  { name: "剁椒鱼头", ingredients: ["鱼头", "剁椒", "姜"], cuisine: "湘菜" },
  { name: "小炒黄牛肉", ingredients: ["牛肉", "辣椒", "香菜"], cuisine: "湘菜" },
  { name: "毛氏红烧肉", ingredients: ["猪肉", "辣椒", "八角"], cuisine: "湘菜" },
  { name: "腊味合蒸", ingredients: ["腊肉", "香肠", "腊鱼"], cuisine: "湘菜" },
  { name: "永州血鸭", ingredients: ["鸭肉", "鸭血", "辣椒"], cuisine: "湘菜" },
  { name: "东安鸡", ingredients: ["鸡肉", "姜", "辣椒"], cuisine: "湘菜" },
  { name: "外婆菜", ingredients: ["萝卜", "梅干菜", "辣椒"], cuisine: "湘菜" },
  { name: "土匪猪肝", ingredients: ["猪肝", "辣椒", "大蒜"], cuisine: "湘菜" },
  { name: "湘西酸肉", ingredients: ["猪肉", "糯米", "辣椒"], cuisine: "湘菜" },
  { name: "组庵鱼翅", ingredients: ["鱼翅", "鸡肉", "猪肉"], cuisine: "湘菜" },
  { name: "发丝牛百叶", ingredients: ["牛百叶", "辣椒", "香菜"], cuisine: "湘菜" },
  { name: "龟羊汤", ingredients: ["羊肉", "龟肉", "药材"], cuisine: "湘菜" },
  { name: "冰糖湘莲", ingredients: ["莲子", "冰糖", "枸杞"], cuisine: "湘菜" },
  { name: "辣椒炒肉", ingredients: ["猪肉", "辣椒", "大蒜"], cuisine: "湘菜" },
  { name: "酸辣鸡杂", ingredients: ["鸡杂", "酸豆角", "辣椒"], cuisine: "湘菜" },
  { name: "擂辣椒皮蛋", ingredients: ["辣椒", "皮蛋", "茄子"], cuisine: "湘菜" },
  { name: "酱香鸭", ingredients: ["鸭肉", "豆瓣酱", "辣椒"], cuisine: "湘菜" },
  { name: "湘味臭豆腐", ingredients: ["豆腐", "辣椒", "蒜"], cuisine: "湘菜" },
  { name: "口味虾", ingredients: ["小龙虾", "辣椒", "紫苏"], cuisine: "湘菜" },
  { name: "剁椒蒸芋头", ingredients: ["芋头", "剁椒", "蒜"], cuisine: "湘菜" },

  // --- 江浙菜 ---
  { name: "西湖醋鱼", ingredients: ["草鱼", "姜", "醋"], cuisine: "江浙菜" },
  { name: "东坡肉", ingredients: ["猪肉", "黄酒", "酱油"], cuisine: "江浙菜" },
  { name: "龙井虾仁", ingredients: ["虾仁", "茶叶"], cuisine: "江浙菜" },
  { name: "叫化鸡", ingredients: ["鸡肉", "香菇", "猪肉"], cuisine: "江浙菜" },
  { name: "糖醋排骨", ingredients: ["猪排骨", "醋", "糖"], cuisine: "江浙菜" },
  { name: "腌笃鲜", ingredients: ["猪肉", "咸肉", "竹笋"], cuisine: "江浙菜" },
  { name: "小笼包", ingredients: ["面粉", "猪肉", "皮冻"], cuisine: "江浙菜" },
  { name: "松鼠桂鱼", ingredients: ["鳜鱼", "松子", "青豆"], cuisine: "江浙菜" },
  { name: "响油鳝糊", ingredients: ["黄鳝", "蒜", "酱油"], cuisine: "江浙菜" },
  { name: "白灼虾", ingredients: ["虾", "姜", "葱"], cuisine: "江浙菜" },
  { name: "油焖笋", ingredients: ["竹笋", "酱油", "糖"], cuisine: "江浙菜" },
  { name: "干炸响铃", ingredients: ["豆腐皮", "猪肉"], cuisine: "江浙菜" },
  { name: "宋嫂鱼羹", ingredients: ["鱼肉", "香菇", "竹笋"], cuisine: "江浙菜" },
  { name: "蜜汁火方", ingredients: ["火腿", "莲子", "蜂蜜"], cuisine: "江浙菜" },
  { name: "清汤鱼圆", ingredients: ["鱼肉", "菜心"], cuisine: "江浙菜" },
  { name: "定胜糕", ingredients: ["米粉", "豆沙"], cuisine: "江浙菜" },
  { name: "宁波汤圆", ingredients: ["糯米粉", "黑芝麻"], cuisine: "江浙菜" },
  { name: "千张包", ingredients: ["千张", "猪肉", "笋"], cuisine: "江浙菜" },
  { name: "糟溜鱼片", ingredients: ["鱼肉", "木耳", "糟卤"], cuisine: "江浙菜" },
  { name: "马兰头拌香干", ingredients: ["马兰头", "豆腐干"], cuisine: "江浙菜" },
  { name: "油爆虾", ingredients: ["河虾", "葱", "姜"], cuisine: "江浙菜" },
  { name: "八宝饭", ingredients: ["糯米", "豆沙", "果脯"], cuisine: "江浙菜" },
  { name: "醉鸡", ingredients: ["鸡肉", "黄酒"], cuisine: "江浙菜" },
  { name: "葱包桧", ingredients: ["面粉", "油条", "葱"], cuisine: "江浙菜" },
  { name: "片儿川", ingredients: ["面条", "猪肉", "笋", "雪菜"], cuisine: "江浙菜" },

  // --- 其他中式菜系 ---
  { name: "北京烤鸭", ingredients: ["鸭肉", "甜面酱", "黄瓜"], cuisine: "京菜" },
  { name: "炸酱面", ingredients: ["面条", "猪肉", "黄瓜", "豆芽"], cuisine: "京菜" },
  { name: "京酱肉丝", ingredients: ["猪肉", "甜面酱", "豆腐皮"], cuisine: "京菜" },
  { name: "涮羊肉", ingredients: ["羊肉", "白菜", "豆腐"], cuisine: "京菜" },
  { name: "卤煮火烧", ingredients: ["猪肠", "猪肺", "火烧"], cuisine: "京菜" },
  { name: "炒肝", ingredients: ["猪肝", "猪肠", "蒜"], cuisine: "京菜" },
  { name: "豆汁儿", ingredients: ["绿豆", "焦圈"], cuisine: "京菜" },
  { name: "驴打滚", ingredients: ["糯米粉", "豆面", "豆沙"], cuisine: "京菜" },
  { name: "天津包子", ingredients: ["面粉", "猪肉"], cuisine: "津菜" },
  { name: "煎饼果子", ingredients: ["绿豆面", "鸡蛋", "油条"], cuisine: "津菜" },
  { name: "锅塌里脊", ingredients: ["猪肉", "鸡蛋"], cuisine: "鲁菜" },
  { name: "松鼠鱼", ingredients: ["鱼", "松子", "青豆"], cuisine: "鲁菜" },
  { name: "三套鸭", ingredients: ["鸭肉", "鸽肉", "鸡肉"], cuisine: "苏菜" },
  { name: "大煮干丝", ingredients: ["豆腐干", "虾仁", "鸡肉"], cuisine: "苏菜" },
  { name: "淮扬软兜", ingredients: ["黄鳝", "蒜", "胡椒"], cuisine: "苏菜" },
  { name: "平桥豆腐", ingredients: ["豆腐", "鸡肉", "香菇"], cuisine: "苏菜" },
  { name: "霸王别姬", ingredients: ["甲鱼", "鸡肉"], cuisine: "徽菜" },
  { name: "符离集烧鸡", ingredients: ["鸡肉", "香料"], cuisine: "徽菜" },
  { name: "黄山炖鸽", ingredients: ["鸽肉", "火腿"], cuisine: "徽菜" },
  { name: "臭鳜鱼", ingredients: ["鳜鱼", "臭豆腐"], cuisine: "徽菜" },
  { name: "毛豆腐", ingredients: ["豆腐", "辣椒酱"], cuisine: "徽菜" },
  { name: "火腿炖甲鱼", ingredients: ["甲鱼", "火腿"], cuisine: "徽菜" },
  { name: "石耳炖鸡", ingredients: ["鸡肉", "石耳"], cuisine: "徽菜" },
  { name: "中和汤", ingredients: ["豆腐", "虾米", "香菇"], cuisine: "徽菜" },
  { name: "福建佛跳墙", ingredients: ["鲍鱼", "海参", "鱼翅", "鸡肉"], cuisine: "闽菜" },
  { name: "福州鱼丸", ingredients: ["鱼肉", "猪肉"], cuisine: "闽菜" },
  { name: "蚵仔煎", ingredients: ["牡蛎", "鸡蛋", "青菜"], cuisine: "闽菜" },
  { name: "沙县拌面", ingredients: ["面条", "花生酱"], cuisine: "闽菜" },
  { name: "沙县扁肉", ingredients: ["猪肉", "面粉"], cuisine: "闽菜" },
  { name: "姜母鸭", ingredients: ["鸭肉", "姜", "药材"], cuisine: "闽菜" },
  { name: "客家酿豆腐", ingredients: ["豆腐", "猪肉", "香菇"], cuisine: "客家菜" },
  { name: "猪肚包鸡", ingredients: ["猪肚", "鸡肉"], cuisine: "客家菜" },
  { name: "潮汕牛肉火锅", ingredients: ["牛肉", "牛丸"], cuisine: "潮汕菜" },
  { name: "潮汕蚝烙", ingredients: ["牡蛎", "鸡蛋"], cuisine: "潮汕菜" },
  { name: "潮汕砂锅粥", ingredients: ["米饭", "海鲜", "肉类"], cuisine: "潮汕菜" },
  { name: "隆江猪脚饭", ingredients: ["猪蹄", "米饭"], cuisine: "潮汕菜" },
  { name: "桂林米粉", ingredients: ["米粉", "牛肉", "花生"], cuisine: "桂菜" },
  { name: "螺蛳粉", ingredients: ["米粉", "螺蛳", "酸笋"], cuisine: "桂菜" },
  { name: "老友粉", ingredients: ["米粉", "猪肉", "酸笋"], cuisine: "桂菜" },
  { name: "柠檬鸭", ingredients: ["鸭肉", "柠檬"], cuisine: "桂菜" },
  { name: "纸包鸡", ingredients: ["鸡肉", "香菇"], cuisine: "桂菜" },
  { name: "海南鸡饭", ingredients: ["鸡肉", "米饭"], cuisine: "琼菜" },
  { name: "椰子鸡", ingredients: ["鸡肉", "椰子"], cuisine: "琼菜" },
  { name: "加积鸭", ingredients: ["鸭肉"], cuisine: "琼菜" },
  { name: "东山羊", ingredients: ["羊肉"], cuisine: "琼菜" },
  { name: "文昌鸡", ingredients: ["鸡肉"], cuisine: "琼菜" },
  { name: "和乐蟹", ingredients: ["螃蟹"], cuisine: "琼菜" },
  { name: "竹筒饭", ingredients: ["米饭", "肉类"], cuisine: "云南菜" },
  { name: "过桥米线", ingredients: ["米线", "鸡肉", "蔬菜"], cuisine: "云南菜" },
  { name: "汽锅鸡", ingredients: ["鸡肉", "药材"], cuisine: "云南菜" },
  { name: "宣威火腿", ingredients: ["猪肉", "盐"], cuisine: "云南菜" },
  { name: "鲜花饼", ingredients: ["面粉", "玫瑰花"], cuisine: "云南菜" },
  { name: "菠萝饭", ingredients: ["米饭", "菠萝", "虾仁"], cuisine: "云南菜" },
  { name: "香茅草烤鱼", ingredients: ["鱼", "香茅草"], cuisine: "云南菜" },
  { name: "傣味手抓饭", ingredients: ["米饭", "肉类"], cuisine: "云南菜" },
  { name: "腊排骨火锅", ingredients: ["腊排骨", "蔬菜"], cuisine: "云南菜" },
  { name: "野生菌火锅", ingredients: ["菌菇", "鸡肉"], cuisine: "云南菜" },
  { name: "牦牛肉干", ingredients: ["牦牛肉"], cuisine: "藏菜" },
  { name: "酥油茶", ingredients: ["酥油", "茶叶"], cuisine: "藏菜" },
  { name: "青稞酒", ingredients: ["青稞"], cuisine: "藏菜" },
  { name: "羊肉泡馍", ingredients: ["羊肉", "面粉"], cuisine: "西北菜" },
  { name: "肉夹馍", ingredients: ["猪肉", "面粉"], cuisine: "西北菜" },
  { name: "凉皮", ingredients: ["面粉", "黄瓜", "豆芽"], cuisine: "西北菜" },
  { name: "biangbiang面", ingredients: ["面粉", "辣椒"], cuisine: "西北菜" },
  { name: "锅盔", ingredients: ["面粉", "猪肉"], cuisine: "西北菜" },
  { name: "臊子面", ingredients: ["面条", "猪肉", "蔬菜"], cuisine: "西北菜" },

  // --- 日料 ---
  { name: "寿司", ingredients: ["米饭", "鱼", "海苔"], cuisine: "日料" },
  { name: "刺身", ingredients: ["鱼", "芥末", "酱油"], cuisine: "日料" },
  { name: "天妇罗", ingredients: ["虾", "蔬菜", "面粉"], cuisine: "日料" },
  { name: "拉面", ingredients: ["面条", "猪肉", "鸡蛋"], cuisine: "日料" },
  { name: "乌冬面", ingredients: ["乌冬面", "牛肉", "蔬菜"], cuisine: "日料" },
  { name: "荞麦面", ingredients: ["荞麦面", "酱油", "海苔"], cuisine: "日料" },
  { name: "亲子丼", ingredients: ["鸡肉", "鸡蛋", "米饭"], cuisine: "日料" },
  { name: "牛丼", ingredients: ["牛肉", "鸡蛋", "米饭"], cuisine: "日料" },
  { name: "照烧鸡排", ingredients: ["鸡肉", "照烧酱"], cuisine: "日料" },
  { name: "唐扬炸鸡", ingredients: ["鸡肉", "面粉"], cuisine: "日料" },
  { name: "寿喜烧", ingredients: ["牛肉", "豆腐", "蔬菜"], cuisine: "日料" },
  { name: "关东煮", ingredients: ["萝卜", "豆腐", "鱼丸"], cuisine: "日料" },
  { name: "茶碗蒸", ingredients: ["鸡蛋", "虾仁", "香菇"], cuisine: "日料" },
  { name: "味增汤", ingredients: ["味增", "豆腐", "海带"], cuisine: "日料" },
  { name: "饭团", ingredients: ["米饭", "海苔", "梅干"], cuisine: "日料" },
  { name: "纳豆", ingredients: ["纳豆", "米饭"], cuisine: "日料" },
  { name: "大阪烧", ingredients: ["面粉", "卷心菜", "猪肉"], cuisine: "日料" },
  { name: "章鱼烧", ingredients: ["面粉", "章鱼", "柴鱼片"], cuisine: "日料" },
  { name: "炸猪排", ingredients: ["猪肉", "面包糠"], cuisine: "日料" },
  { name: "鳗鱼饭", ingredients: ["鳗鱼", "米饭"], cuisine: "日料" },
  { name: "鸡肉串", ingredients: ["鸡肉", "大葱"], cuisine: "日料" },
  { name: "牛肉串", ingredients: ["牛肉", "青椒"], cuisine: "日料" },
  { name: "烤秋刀鱼", ingredients: ["秋刀鱼", "萝卜"], cuisine: "日料" },
  { name: "茶泡饭", ingredients: ["米饭", "茶", "海苔"], cuisine: "日料" },
  { name: "日式咖喱", ingredients: ["肉类", "土豆", "胡萝卜"], cuisine: "日料" },
  { name: "筑前煮", ingredients: ["鸡肉", "根菜"], cuisine: "日料" },
  { name: "土豆炖肉", ingredients: ["猪肉", "土豆", "洋葱"], cuisine: "日料" },
  { name: "金平牛蒡", ingredients: ["牛蒡", "胡萝卜"], cuisine: "日料" },
  { name: "凉拌菠菜", ingredients: ["菠菜", "柴鱼片"], cuisine: "日料" },
  { name: "冷豆腐", ingredients: ["豆腐", "葱", "姜"], cuisine: "日料" },
  { name: "御好烧", ingredients: ["面粉", "卷心菜", "海鲜"], cuisine: "日料" },
  { name: "炸虾", ingredients: ["虾", "面粉"], cuisine: "日料" },
  { name: "鲷鱼烧", ingredients: ["面粉", "豆沙"], cuisine: "日料" },
  { name: "大福", ingredients: ["糯米粉", "豆沙"], cuisine: "日料" },
  { name: "羊羹", ingredients: ["红豆", "寒天"], cuisine: "日料" },
  { name: "团子", ingredients: ["糯米粉", "酱油"], cuisine: "日料" },
  { name: "铜锣烧", ingredients: ["面粉", "豆沙"], cuisine: "日料" },
  { name: "长崎蛋糕", ingredients: ["面粉", "鸡蛋", "糖"], cuisine: "日料" },
  { name: "水信玄饼", ingredients: ["琼脂", "黑糖"], cuisine: "日料" },

  // --- 韩料 ---
  { name: "韩式烤肉", ingredients: ["牛肉", "生菜", "大蒜"], cuisine: "韩料" },
  { name: "泡菜", ingredients: ["白菜", "辣椒粉", "蒜"], cuisine: "韩料" },
  { name: "石锅拌饭", ingredients: ["米饭", "牛肉", "蔬菜"], cuisine: "韩料" },
  { name: "大酱汤", ingredients: ["大酱", "豆腐", "蔬菜"], cuisine: "韩料" },
  { name: "部队锅", ingredients: ["火腿", "午餐肉", "泡菜"], cuisine: "韩料" },
  { name: "参鸡汤", ingredients: ["鸡肉", "糯米", "人参"], cuisine: "韩料" },
  { name: "韩式炸鸡", ingredients: ["鸡肉", "辣椒酱"], cuisine: "韩料" },
  { name: "炒年糕", ingredients: ["年糕", "鱼饼", "辣椒酱"], cuisine: "韩料" },
  { name: "海鲜葱饼", ingredients: ["面粉", "葱", "海鲜"], cuisine: "韩料" },
  { name: "韩式猪蹄", ingredients: ["猪蹄", "生菜"], cuisine: "韩料" },
  { name: "冷面", ingredients: ["荞麦面", "牛肉", "梨"], cuisine: "韩料" },
  { name: "韩式拌饭", ingredients: ["米饭", "牛肉", "蔬菜"], cuisine: "韩料" },
  { name: "辣炒猪肉", ingredients: ["猪肉", "辣椒酱"], cuisine: "韩料" },
  { name: "韩式血肠", ingredients: ["猪肠", "糯米", "蔬菜"], cuisine: "韩料" },
  { name: "韩式蒸排骨", ingredients: ["猪排骨", "辣椒酱"], cuisine: "韩料" },
  { name: "韩式炖鸡", ingredients: ["鸡肉", "土豆", "胡萝卜"], cuisine: "韩料" },
  { name: "韩式鱼糕", ingredients: ["鱼肉", "面粉"], cuisine: "韩料" },
  { name: "韩式泡菜饼", ingredients: ["面粉", "泡菜"], cuisine: "韩料" },
  { name: "韩式豆腐汤", ingredients: ["豆腐", "海鲜", "辣椒"], cuisine: "韩料" },
  { name: "韩式腌螃蟹", ingredients: ["螃蟹", "酱油"], cuisine: "韩料" },
  { name: "韩式酱蟹", ingredients: ["螃蟹", "辣椒酱"], cuisine: "韩料" },
  { name: "韩式生拌牛肉", ingredients: ["牛肉", "梨", "芝麻"], cuisine: "韩料" },
  { name: "韩式米肠", ingredients: ["糯米", "猪肠"], cuisine: "韩料" },
  { name: "韩式南瓜粥", ingredients: ["南瓜", "糯米"], cuisine: "韩料" },
  { name: "韩式甜米露", ingredients: ["大米", "麦芽"], cuisine: "韩料" },

  // --- 东南亚菜 ---
  { name: "泰式冬阴功", ingredients: ["虾", "蘑菇", "香茅"], cuisine: "东南亚" },
  { name: "泰式绿咖喱", ingredients: ["鸡肉", "茄子", "椰奶"], cuisine: "东南亚" },
  { name: "泰式炒河粉", ingredients: ["河粉", "虾", "豆芽"], cuisine: "东南亚" },
  { name: "泰式木瓜沙拉", ingredients: ["木瓜", "虾", "花生"], cuisine: "东南亚" },
  { name: "泰式柠檬鱼", ingredients: ["鱼", "柠檬", "辣椒"], cuisine: "东南亚" },
  { name: "泰式打抛猪肉", ingredients: ["猪肉", "罗勒", "辣椒"], cuisine: "东南亚" },
  { name: "泰式椰汁鸡汤", ingredients: ["鸡肉", "椰奶", "蘑菇"], cuisine: "东南亚" },
  { name: "泰式红咖喱", ingredients: ["肉类", "蔬菜", "椰奶"], cuisine: "东南亚" },
  { name: "泰式黄咖喱", ingredients: ["肉类", "土豆", "椰奶"], cuisine: "东南亚" },
  { name: "泰式芒果糯米饭", ingredients: ["芒果", "糯米", "椰奶"], cuisine: "东南亚" },
  { name: "越南河粉", ingredients: ["米粉", "牛肉", "香草"], cuisine: "东南亚" },
  { name: "越南春卷", ingredients: ["米纸", "虾", "蔬菜"], cuisine: "东南亚" },
  { name: "越南法棍三明治", ingredients: ["面包", "猪肉", "蔬菜"], cuisine: "东南亚" },
  { name: "越南烤肉米粉", ingredients: ["米粉", "猪肉", "鱼露"], cuisine: "东南亚" },
  { name: "越南甘蔗虾", ingredients: ["虾", "甘蔗", "面粉"], cuisine: "东南亚" },
  { name: "新加坡海南鸡饭", ingredients: ["鸡肉", "米饭"], cuisine: "东南亚" },
  { name: "新加坡辣椒螃蟹", ingredients: ["螃蟹", "辣椒", "番茄"], cuisine: "东南亚" },
  { name: "新加坡肉骨茶", ingredients: ["猪排骨", "药材"], cuisine: "东南亚" },
  { name: "新加坡叻沙", ingredients: ["米粉", "虾", "椰奶"], cuisine: "东南亚" },
  { name: "马来西亚椰浆饭", ingredients: ["米饭", "椰奶", "小鱼干"], cuisine: "东南亚" },
  { name: "马来西亚沙爹", ingredients: ["鸡肉", "花生酱"], cuisine: "东南亚" },
  { name: "印尼炒饭", ingredients: ["米饭", "鸡肉", "虾"], cuisine: "东南亚" },
  { name: "印尼沙爹", ingredients: ["鸡肉", "花生酱"], cuisine: "东南亚" },
  { name: "印尼巴东牛肉", ingredients: ["牛肉", "椰奶", "香料"], cuisine: "东南亚" },
  { name: "菲律宾烤猪", ingredients: ["猪肉", "香料"], cuisine: "东南亚" },
  { name: "菲律宾阿斗波", ingredients: ["鸡肉", "醋", "酱油"], cuisine: "东南亚" },
  { name: "菲律宾酸汤", ingredients: ["猪肉", "酸豆"], cuisine: "东南亚" },
  { name: "柬埔寨阿莫克", ingredients: ["鱼", "椰奶", "香料"], cuisine: "东南亚" },
  { name: "缅甸茶叶沙拉", ingredients: ["茶叶", "花生", "芝麻"], cuisine: "东南亚" },
  { name: "老挝拉帕", ingredients: ["木瓜", "鱼露"], cuisine: "东南亚" },
  { name: "缅甸椰汁面", ingredients: ["面条", "椰奶", "鸡肉"], cuisine: "东南亚" },
  { name: "菲律宾哈罗哈罗", ingredients: ["豆类", "椰奶"], cuisine: "东南亚" },
  { name: "泰国椰丝煎饼", ingredients: ["面粉", "椰丝"], cuisine: "东南亚" },
  { name: "越南咖啡", ingredients: ["咖啡", "炼乳"], cuisine: "东南亚" },
  { name: "泰式奶茶", ingredients: ["红茶", "炼乳"], cuisine: "东南亚" },

  // --- 印度及中东菜 ---
  { name: "印度咖喱鸡", ingredients: ["鸡肉", "番茄", "咖喱"], cuisine: "印度" },
  { name: "印度烤饼", ingredients: ["面粉", "黄油"], cuisine: "印度" },
  { name: "印度比尔亚尼饭", ingredients: ["米饭", "鸡肉", "香料"], cuisine: "印度" },
  { name: "印度唐杜里烤鸡", ingredients: ["鸡肉", "酸奶", "香料"], cuisine: "印度" },
  { name: "印度菠菜奶酪", ingredients: ["菠菜", "奶酪"], cuisine: "印度" },
  { name: "印度炸蔬菜", ingredients: ["蔬菜", "面粉"], cuisine: "印度" },
  { name: "印度酸奶", ingredients: ["酸奶", "黄瓜"], cuisine: "印度" },
  { name: "印度香料茶", ingredients: ["茶叶", "香料", "牛奶"], cuisine: "印度" },
  { name: "中东烤肉", ingredients: ["羊肉", "饼", "蔬菜"], cuisine: "中东" },
  { name: "鹰嘴豆泥", ingredients: ["鹰嘴豆", "芝麻酱"], cuisine: "中东" },
  { name: "法拉费", ingredients: ["鹰嘴豆", "香料"], cuisine: "中东" },
  { name: "塔布勒沙拉", ingredients: ["薄荷"], cuisine: "中东" },
  { name: "沙威玛", ingredients: ["肉类", "饼", "蔬菜"], cuisine: "中东" },
  { name: "库斯库斯", ingredients: ["库斯库斯", "蔬菜", "肉类"], cuisine: "中东" },
  { name: "中东茄子泥", ingredients: ["茄子", "芝麻酱"], cuisine: "中东" },
  { name: "葡萄叶卷", ingredients: ["葡萄叶", "米饭", "肉类"], cuisine: "中东" },
  { name: "皮塔饼", ingredients: ["面粉", "芝麻"], cuisine: "中东" },
  { name: "哈尔瓦", ingredients: ["芝麻", "糖"], cuisine: "中东" },
  { name: "巴克拉瓦", ingredients: ["面粉", "坚果", "蜂蜜"], cuisine: "中东" },
  { name: "土耳其咖啡", ingredients: ["咖啡", "糖"], cuisine: "中东" },

  // --- 法式 ---
  { name: "法式焗蜗牛", ingredients: ["蜗牛", "黄油", "蒜"], cuisine: "法式" },
  { name: "法式洋葱汤", ingredients: ["洋葱", "牛肉汤", "面包"], cuisine: "法式" },
  { name: "法式烤鸡", ingredients: ["鸡肉", "土豆", "胡萝卜"], cuisine: "法式" },
  { name: "红酒炖牛肉", ingredients: ["牛肉", "红酒", "蘑菇"], cuisine: "法式" },
  { name: "法式鸭胸", ingredients: ["鸭肉", "橙子"], cuisine: "法式" },
  { name: "法式牛排", ingredients: ["牛肉", "黄油", "香草"], cuisine: "法式" },
  { name: "法式鱼汤", ingredients: ["鱼肉", "番茄", "藏红花"], cuisine: "法式" },
  { name: "法式 quiche", ingredients: ["鸡蛋", "奶油", "培根"], cuisine: "法式" },
  { name: "法式吐司", ingredients: ["面包", "鸡蛋", "牛奶"], cuisine: "法式" },
  { name: "奶油蘑菇汤", ingredients: ["蘑菇", "奶油", "洋葱"], cuisine: "法式" },
  { name: "马赛鱼汤", ingredients: ["鱼肉", "番茄", "香料"], cuisine: "法式" },
  { name: "勃艮第牛肉", ingredients: ["牛肉", "红酒", "蘑菇"], cuisine: "法式" },
  { name: "阿尔萨斯酸菜", ingredients: ["猪肉", "酸菜", "土豆"], cuisine: "法式" },
  { name: "尼斯沙拉", ingredients: ["金枪鱼", "鸡蛋", "蔬菜"], cuisine: "法式" },
  { name: "普罗旺斯炖菜", ingredients: ["茄子", "西葫芦", "番茄"], cuisine: "法式" },
  { name: "法式海鲜拼盘", ingredients: ["海鲜"], cuisine: "法式" },
  { name: "法式焦糖布丁", ingredients: ["奶油", "鸡蛋", "糖"], cuisine: "法式" },
  { name: "马卡龙", ingredients: ["杏仁粉", "糖"], cuisine: "法式" },
  { name: "可丽饼", ingredients: ["面粉", "鸡蛋", "牛奶"], cuisine: "法式" },
  { name: "法式长棍面包", ingredients: ["面粉", "水", "酵母"], cuisine: "法式" },
  { name: "国王饼", ingredients: ["面粉", "杏仁馅"], cuisine: "法式" },
  { name: "歌剧蛋糕", ingredients: ["咖啡", "巧克力", "杏仁"], cuisine: "法式" },
  { name: "慕斯蛋糕", ingredients: ["奶油", "巧克力", "水果"], cuisine: "法式" },
  { name: "泡芙", ingredients: ["面粉", "鸡蛋", "奶油"], cuisine: "法式" },
  { name: "舒芙蕾", ingredients: ["鸡蛋", "糖", "巧克力"], cuisine: "法式" },

  // --- 意式 ---
  { name: "意大利面", ingredients: ["面条", "番茄", "牛肉"], cuisine: "意式" },
  { name: "披萨", ingredients: ["面粉", "番茄", "奶酪"], cuisine: "意式" },
  { name: "意大利烩饭", ingredients: ["米饭", "高汤", "蘑菇"], cuisine: "意式" },
  { name: "千层面", ingredients: ["面条", "牛肉", "奶酪"], cuisine: "意式" },
  { name: "意大利烤面包", ingredients: ["面包", "番茄", "罗勒"], cuisine: "意式" },
  { name: "意式肉丸", ingredients: ["牛肉", "面包屑", "番茄"], cuisine: "意式" },
  { name: "意式炖小牛膝", ingredients: ["小牛膝", "红酒", "蔬菜"], cuisine: "意式" },
  { name: "意式海鲜汤", ingredients: ["海鲜", "番茄", "香草"], cuisine: "意式" },
  { name: "卡普里沙拉", ingredients: ["番茄", "奶酪", "罗勒"], cuisine: "意式" },
  { name: "帕尔玛火腿", ingredients: ["火腿", "哈密瓜"], cuisine: "意式" },
  { name: "意式烤蔬菜", ingredients: ["茄子", "西葫芦", "番茄"], cuisine: "意式" },
  { name: "提拉米苏", ingredients: ["咖啡", "奶酪", "手指饼"], cuisine: "意式" },
  { name: "意式奶冻", ingredients: ["奶油", "糖", "香草"], cuisine: "意式" },
  { name: "意式冰淇淋", ingredients: ["牛奶", "糖", "水果"], cuisine: "意式" },
  { name: "意式咖啡", ingredients: ["咖啡", "牛奶"], cuisine: "意式" },
  { name: "意式煎小牛肉", ingredients: ["小牛肉", "柠檬"], cuisine: "意式" },
  { name: "意式香醋烤鸡", ingredients: ["鸡肉", "香醋", "香草"], cuisine: "意式" },
  { name: "意式土豆丸子", ingredients: ["土豆", "面粉", "奶酪"], cuisine: "意式" },
  { name: "意式面包沙拉", ingredients: ["面包", "番茄", "黄瓜"], cuisine: "意式" },
  { name: "意式炖羊肉", ingredients: ["羊肉", "番茄", "香草"], cuisine: "意式" },
  { name: "意式烤鱼", ingredients: ["鱼", "香草", "柠檬"], cuisine: "意式" },
  { name: "意式蔬菜汤", ingredients: ["蔬菜", "豆类"], cuisine: "意式" },
  { name: "意式炸饭球", ingredients: ["米饭", "奶酪", "肉"], cuisine: "意式" },
  { name: "意式杏仁饼", ingredients: ["杏仁", "糖"], cuisine: "意式" },
  { name: "意式柠檬酒", ingredients: ["柠檬", "糖"], cuisine: "意式" },

  // --- 美式 ---
  { name: "汉堡", ingredients: ["牛肉", "面包", "奶酪"], cuisine: "美式" },
  { name: "热狗", ingredients: ["香肠", "面包", "酱料"], cuisine: "美式" },
  { name: "美式烤肉", ingredients: ["猪肉", "烤肉酱"], cuisine: "美式" },
  { name: "美式炸鸡", ingredients: ["鸡肉", "面粉", "香料"], cuisine: "美式" },
  { name: "美式牛排", ingredients: ["牛肉", "土豆", "蔬菜"], cuisine: "美式" },
  { name: "美式培根", ingredients: ["猪肉", "香料"], cuisine: "美式" },
  { name: "美式早餐", ingredients: ["鸡蛋", "培根", "面包"], cuisine: "美式" },
  { name: "美式披萨", ingredients: ["面粉", "奶酪", "肉"], cuisine: "美式" },
  { name: "美式薯条", ingredients: ["土豆", "油", "盐"], cuisine: "美式" },
  { name: "美式奶昔", ingredients: ["冰淇淋", "牛奶"], cuisine: "美式" },
  { name: "美式苹果派", ingredients: ["苹果", "面粉", "糖"], cuisine: "美式" },
  { name: "美式布朗尼", ingredients: ["巧克力", "面粉", "坚果"], cuisine: "美式" },
  { name: "美式芝士蛋糕", ingredients: ["奶酪", "饼干", "水果"], cuisine: "美式" },
  { name: "美式甜甜圈", ingredients: ["面粉", "糖", "巧克力"], cuisine: "美式" },
  { name: "美式松饼", ingredients: ["面粉", "牛奶", "鸡蛋"], cuisine: "美式" },
  { name: "美式华夫饼", ingredients: ["面粉", "鸡蛋", "牛奶"], cuisine: "美式" },
  { name: "美式玉米面包", ingredients: ["玉米粉", "牛奶", "鸡蛋"], cuisine: "美式" },
  { name: "美式炖牛肉", ingredients: ["牛肉", "胡萝卜", "土豆"], cuisine: "美式" },
  { name: "美式海鲜浓汤", ingredients: ["海鲜", "奶油", "土豆"], cuisine: "美式" },
  { name: "美式烤肋排", ingredients: ["猪肋排", "烧烤酱"], cuisine: "美式" },
  { name: "美式炸鱼薯条", ingredients: ["鱼", "土豆", "面粉"], cuisine: "美式" },
  { name: "美式通心粉沙拉", ingredients: ["通心粉", "蔬菜", "酱"], cuisine: "美式" },
  { name: "美式土豆沙拉", ingredients: ["土豆", "鸡蛋", "酱"], cuisine: "美式" },
  { name: "美式烤豆", ingredients: ["豆类", "培根", "糖"], cuisine: "美式" },
  { name: "美式南瓜派", ingredients: ["南瓜", "面粉", "香料"], cuisine: "美式" },

  // --- 其他西式 ---
  { name: "西班牙海鲜饭", ingredients: ["米饭", "海鲜", "藏红花"], cuisine: "西式" },
  { name: "西班牙 tapas", ingredients: ["小食"], cuisine: "西式" },
  { name: "西班牙火腿", ingredients: ["猪肉", "盐"], cuisine: "西式" },
  { name: "西班牙土豆蛋饼", ingredients: ["土豆", "鸡蛋", "洋葱"], cuisine: "西式" },
  { name: "西班牙冷汤", ingredients: ["番茄", "黄瓜", "面包"], cuisine: "西式" },
  { name: "葡萄牙蛋挞", ingredients: ["面粉", "鸡蛋", "牛奶"], cuisine: "西式" },
  { name: "葡式烤鸡", ingredients: ["鸡肉", "辣椒", "香料"], cuisine: "西式" },
  { name: "葡式海鲜粥", ingredients: ["米饭", "海鲜", "香菜"], cuisine: "西式" },
  { name: "葡式炖猪肉", ingredients: ["猪肉", "蛤蜊"], cuisine: "西式" },
  { name: "德国猪肘", ingredients: ["猪肘", "土豆", "酸菜"], cuisine: "西式" },
  { name: "德国香肠", ingredients: ["猪肉", "香料"], cuisine: "西式" },
  { name: "德国土豆沙拉", ingredients: ["土豆", "培根", "醋"], cuisine: "西式" },
  { name: "德国黑森林蛋糕", ingredients: ["巧克力", "樱桃", "奶油"], cuisine: "西式" },
  { name: "德国苹果卷", ingredients: ["苹果", "面粉", "肉桂"], cuisine: "西式" },
  { name: "英国炸鱼薯条", ingredients: ["鱼", "土豆", "面粉"], cuisine: "西式" },
  { name: "英式早餐", ingredients: ["鸡蛋", "培根", "豆子"], cuisine: "西式" },
  { name: "英式烤牛肉", ingredients: ["牛肉", "土豆", "蔬菜"], cuisine: "西式" },
  { name: "英式司康饼", ingredients: ["面粉", "牛奶", "果干"], cuisine: "西式" },
  { name: "英式苹果酥", ingredients: ["苹果", "面粉", "黄油"], cuisine: "西式" },
  { name: "爱尔兰炖肉", ingredients: ["羊肉", "土豆", "胡萝卜"], cuisine: "西式" },
  { name: "爱尔兰咖啡", ingredients: ["咖啡", "威士忌", "奶油"], cuisine: "西式" },
  { name: "苏格兰蛋", ingredients: ["鸡蛋", "猪肉", "面包屑"], cuisine: "西式" },
  { name: "苏格兰 shortbread", ingredients: ["面粉", "黄油", "糖"], cuisine: "西式" },
  { name: "希腊沙拉", ingredients: ["番茄", "黄瓜", "奶酪"], cuisine: "西式" },
  { name: "希腊烤肉", ingredients: ["猪肉", "饼", "蔬菜"], cuisine: "西式" },
  { name: "希腊 moussaka", ingredients: ["茄子", "羊肉", "奶酪"], cuisine: "西式" },
  { name: "希腊酸奶", ingredients: ["牛奶"], cuisine: "西式" },
  { name: "希腊果仁蜜饼", ingredients: ["面粉", "坚果", "蜂蜜"], cuisine: "西式" },
  { name: "俄罗斯罗宋汤", ingredients: ["牛肉", "甜菜", "土豆"], cuisine: "西式" },
  { name: "俄罗斯奥利维尔沙拉", ingredients: ["土豆", "胡萝卜", "鸡肉"], cuisine: "西式" },
  { name: "俄罗斯饺子", ingredients: ["面粉", "猪肉", "牛肉"], cuisine: "西式" },
  { name: "俄罗斯烤肉串", ingredients: ["猪肉", "洋葱"], cuisine: "西式" },
  { name: "瑞典肉丸", ingredients: ["牛肉", "奶油", "果酱"], cuisine: "西式" },
  { name: "瑞士奶酪火锅", ingredients: ["奶酪", "面包"], cuisine: "西式" },
  { name: "瑞士巧克力", ingredients: ["可可", "牛奶", "糖"], cuisine: "西式" },
  { name: "比利时华夫饼", ingredients: ["面粉", "鸡蛋", "糖"], cuisine: "西式" },
  { name: "比利时巧克力", ingredients: ["可可", "牛奶", "糖"], cuisine: "西式" },
  { name: "比利时啤酒炖牛肉", ingredients: ["牛肉", "啤酒", "蔬菜"], cuisine: "西式" },
  { name: "荷兰煎饼", ingredients: ["面粉", "牛奶", "鸡蛋"], cuisine: "西式" },
  { name: "荷兰奶酪", ingredients: ["牛奶", "盐"], cuisine: "西式" },
  { name: "波兰饺子", ingredients: ["面粉", "土豆", "奶酪"], cuisine: "西式" },
  { name: "匈牙利炖牛肉", ingredients: ["牛肉", "土豆", "辣椒"], cuisine: "西式" },
  { name: "捷克烤猪肉", ingredients: ["猪肉", "饺子", "酸菜"], cuisine: "西式" },
  { name: "奥地利苹果卷", ingredients: ["苹果", "面粉", "肉桂"], cuisine: "西式" },
  { name: "维也纳炸猪排", ingredients: ["猪肉", "面包屑"], cuisine: "西式" },

  // --- 烧烤类 ---
  { name: "新疆羊肉串", ingredients: ["羊肉", "孜然", "辣椒"], cuisine: "烧烤" },
  { name: "巴西烤肉", ingredients: ["牛肉", "盐"], cuisine: "烧烤" },
  { name: "阿根廷烤肉", ingredients: ["牛肉", "酱"], cuisine: "烧烤" },
  { name: "蒙古烤肉", ingredients: ["羊肉", "洋葱"], cuisine: "烧烤" },
  { name: "日式烧鸟", ingredients: ["鸡肉", "大葱", "酱汁"], cuisine: "烧烤" },
  { name: "美式烧烤", ingredients: ["猪肉", "烧烤酱"], cuisine: "烧烤" },
  { name: "德式烤猪肘", ingredients: ["猪肘", "土豆"], cuisine: "烧烤" },
  { name: "泰式烤鱼", ingredients: ["鱼", "香茅", "柠檬"], cuisine: "烧烤" },
  { name: "越南烤猪肉", ingredients: ["猪肉", "鱼露", "香茅"], cuisine: "烧烤" },
  { name: "印度烤鸡", ingredients: ["鸡肉", "酸奶", "香料"], cuisine: "烧烤" },
  { name: "中东烤肉串", ingredients: ["羊肉", "饼", "蔬菜"], cuisine: "烧烤" },
  { name: "非洲烤肉", ingredients: ["羊肉", "花生酱"], cuisine: "烧烤" },
  { name: "加勒比烤鸡", ingredients: ["鸡肉", "香料", "水果"], cuisine: "烧烤" },
  { name: "夏威夷烤猪", ingredients: ["猪肉", "香蕉叶"], cuisine: "烧烤" },
  { name: "菲律宾烤乳猪", ingredients: ["猪肉", "香料"], cuisine: "烧烤" },
  { name: "马来西亚烤鱼", ingredients: ["鱼", "香料", "香蕉叶"], cuisine: "烧烤" },
  { name: "缅甸烤牛肉", ingredients: ["牛肉", "香料"], cuisine: "烧烤" },
  { name: "老挝烤鸡", ingredients: ["鸡肉", "香料"], cuisine: "烧烤" },

  // --- 火锅类 ---
  { name: "重庆火锅", ingredients: ["牛肉", "毛肚", "豆皮"], cuisine: "火锅" },
  { name: "北京涮羊肉", ingredients: ["羊肉", "白菜", "豆腐"], cuisine: "火锅" },
  { name: "云南野生菌火锅", ingredients: ["菌菇", "鸡肉"], cuisine: "火锅" },
  { name: "韩式部队锅", ingredients: ["火腿", "泡菜", "面条"], cuisine: "火锅" },
  { name: "日式寿喜烧", ingredients: ["牛肉", "豆腐", "蔬菜"], cuisine: "火锅" },
  { name: "泰式冬阴功火锅", ingredients: ["虾", "蘑菇", "香茅"], cuisine: "火锅" },
  { name: "印度咖喱火锅", ingredients: ["鸡肉", "蔬菜", "咖喱"], cuisine: "火锅" },
  { name: "巧克力火锅", ingredients: ["巧克力", "水果"], cuisine: "火锅" },
  { name: "海鲜火锅", ingredients: ["虾", "鱼", "贝类"], cuisine: "火锅" },
  { name: "粥底火锅", ingredients: ["粥", "海鲜", "肉类"], cuisine: "火锅" },
  { name: "酸菜白肉火锅", ingredients: ["猪肉", "酸菜", "血肠"], cuisine: "火锅" },
  { name: "羊肉火锅", ingredients: ["羊肉", "萝卜", "腐竹"], cuisine: "火锅" },
  { name: "麻辣烫", ingredients: ["蔬菜", "肉类", "豆制品"], cuisine: "火锅" },

  // --- 素食类 ---
  { name: "素斋", ingredients: ["豆腐", "香菇", "蔬菜"], cuisine: "素食" },
  { name: "罗汉斋", ingredients: ["蔬菜", "菌菇"], cuisine: "素食" },
  { name: "素麻婆豆腐", ingredients: ["豆腐", "香菇", "辣椒"], cuisine: "素食" },
  { name: "素回锅肉", ingredients: ["面筋", "青椒", "豆瓣酱"], cuisine: "素食" },
  { name: "素鱼香肉丝", ingredients: ["木耳", "胡萝卜", "笋丝"], cuisine: "素食" },
  { name: "素宫保鸡丁", ingredients: ["面筋", "花生", "辣椒"], cuisine: "素食" },
  { name: "素水煮鱼", ingredients: ["豆皮", "豆芽", "辣椒"], cuisine: "素食" },
  { name: "素烤鸭", ingredients: ["豆腐皮", "香菇"], cuisine: "素食" },
  { name: "素东坡肉", ingredients: ["冬瓜", "香菇"], cuisine: "素食" },
  { name: "素狮子头", ingredients: ["豆腐", "香菇", "荸荠"], cuisine: "素食" },
  { name: "素饺子", ingredients: ["面粉", "蔬菜", "香菇"], cuisine: "素食" },
  { name: "素包子", ingredients: ["面粉", "蔬菜", "豆腐"], cuisine: "素食" },
  { name: "素炒饭", ingredients: ["米饭", "蔬菜", "鸡蛋"], cuisine: "素食" },
  { name: "素沙拉", ingredients: ["蔬菜", "水果"], cuisine: "素食" },
  { name: "素汤", ingredients: ["蔬菜", "菌菇"], cuisine: "素食" },
  { name: "素咖喱", ingredients: ["土豆", "胡萝卜", "椰奶"], cuisine: "素食" },
  { name: "素披萨", ingredients: ["面粉", "蔬菜", "奶酪"], cuisine: "素食" },
  { name: "素汉堡", ingredients: ["豆饼", "蔬菜", "面包"], cuisine: "素食" },
  { name: "素寿司", ingredients: ["米饭", "蔬菜", "海苔"], cuisine: "素食" },
  { name: "素春卷", ingredients: ["米纸", "蔬菜", "香菇"], cuisine: "素食" },

  // --- 主食类 ---
  { name: "扬州炒饭", ingredients: ["米饭", "虾仁", "火腿"], cuisine: "主食" },
  { name: "新疆手抓饭", ingredients: ["米饭", "羊肉", "胡萝卜"], cuisine: "主食" },
  { name: "韩国拌饭", ingredients: ["米饭", "牛肉", "蔬菜"], cuisine: "主食" },
  { name: "泰国菠萝饭", ingredients: ["米饭", "菠萝", "虾仁"], cuisine: "主食" },
  { name: "墨西哥卷饼", ingredients: ["饼", "牛肉", "蔬菜"], cuisine: "主食" },
  { name: "美国汉堡", ingredients: ["面包", "牛肉", "奶酪"], cuisine: "主食" },
  { name: "法国可丽饼", ingredients: ["面粉", "鸡蛋", "馅料"], cuisine: "主食" },
  { name: "中国饺子", ingredients: ["面粉", "猪肉", "蔬菜"], cuisine: "主食" },
  { name: "中国包子", ingredients: ["面粉", "猪肉", "蔬菜"], cuisine: "主食" },
  { name: "中国面条", ingredients: ["面粉", "肉类", "蔬菜"], cuisine: "主食" },
  { name: "马来西亚炒粿条", ingredients: ["米粉", "虾", "豆芽"], cuisine: "主食" },
  { name: "菲律宾炒面", ingredients: ["面条", "猪肉", "蔬菜"], cuisine: "主食" },
  { name: "缅甸鱼汤米线", ingredients: ["米线", "鱼"], cuisine: "主食" },
  { name: "老挝米粉", ingredients: ["米粉", "牛肉", "香草"], cuisine: "主食" },
  { name: "柬埔寨米粉", ingredients: ["米粉", "鱼肉", "豆芽"], cuisine: "主食" },
  { name: "尼泊尔馍馍", ingredients: ["面粉", "牛肉", "蔬菜"], cuisine: "主食" },
  { name: "西藏糌粑", ingredients: ["青稞粉", "酥油茶"], cuisine: "主食" },
  { name: "蒙古包子", ingredients: ["面粉", "羊肉", "洋葱"], cuisine: "主食" }
];
